const releasesData = 
[
	{
		id: 1,
		name: "Twisting Skies",
		albumName: "VA - The Phantom Troupe",
		releaseYear: 2016,
		project: "Sound Curious",
		cover:require('./images/thePhantomTroupe.jpg'),
	},
	{
		id: 2,
		name: "Seeking Entropy",
		albumName: "VA - Echoes in the Dark",
		releaseYear: 2018,
		project: "Tenebral Cortex",
		cover:require('./images/echoesInTheDark.jpg'),
	},
	{
		id: 3,
		name: "Digital Absolution",
		albumName: "VA - Prodigal Dawn",
		releaseYear: 2018,
		project: "Sound Curious",
		cover:require("./images/digitalAbsolution.jpg") ,
	},
	{
		id: 4,
		name: "Regrained Misconceptions",
		albumName: "VA - First Signal",
		releaseYear: 2017,
		project: "Sound Curious",
		cover:require("./images/regrainedMisconceptions.png") ,
	},
	{
		id: 5,
		name: "Ignorance is Bliss",
		albumName: "VA - The Psycho Asylum - From (A)thens with Hate Vol.1",
		releaseYear: 2013,
		project: "Sound Curious & Fear Disorder",
		cover:require("./images/ignoranceIsBliss.jpg") ,
	},
	{
		id: 6,
		name: "Lost Between Dimensions",
		albumName: "VA - Minuteless",
		releaseYear: 2019,
		project: "Tenebral Cortex",
		cover:require("./images/minuteless1.jpg") ,
	},
	{
		id: 7,
		name: "The Devolution of the Mind",
		albumName: "VA - The Psycho Asylum - Dark Block Attack! Vol.2",
		releaseYear: 2017,
		project: "Sound Curious",
		cover:require("./images/theDevolutionOfTheMind.jpg") ,
	},
	{
		id: 8,
		name: "68656c70206d65",
		albumName: "VA - Hadron Collider",
		releaseYear: 2018,
		project: "Sound Curious",
		cover:require("./images/hm.jpg") ,
	},
	{
		id: 9,
		name: "Krakatoa Blast",
		albumName: "VA - Mechanical Madness",
		releaseYear: 2016,
		project: "Sound Curious & Critical Freak & Parakustik",
		cover:require("./images/krakatoaBlast.jpg") ,
	},
	{
		id: 10,
		name: "Ephémère",
		albumName: "VA - Night of Sacrifice",
		releaseYear: 2018,
		project: "Sound Curious",
		cover:require("./images/nightOfSacrifice.png") ,
	},
	{
		id: 11,
		name: "Solo Album",
		albumName: "Arduous Recursion",
		releaseYear: 2020,
		project: "Tenebral Cortex",
		cover:require("./images/arduousRecursion.jpg") ,
	},
]

export default releasesData